# 异步代码的测试方法

在JavaScript中，代码以异步方式运行是很常见的。当您拥有异步运行的代码时，Jest需要知道它正在测试的代码何时完成，然后才能继续进行另一个测试。 Jest有几种方法可以解决这个问题。

## 回调

最常见的异步模式是回调函数

例如，假设您有一个 ```fetchData(callback)``` 函数，获取一些数据并在完成时调用 ```callback(data)```。 你想要测试返回的数据是'peanut butter'

默认情况下当fetchData执行完成的时候Jest的测试就完成了，这并不是你所期望的那样的去运行。

```javascript
// Don't do this!
test('the data is peanut butter', () => {
    function callback(data) {
        expect(data).toBe('peanut butter');
    }

    fetchData(callback);
});
```

上面的代码问题在于，一旦fetchData执行结束，此测试就在没有调用回调函数前结束。测试直接通过了。

Jest提供了一种用于测试回调函数的方法。 不要将测试放在具有空参数的函数中，而是使用名为done的单个参数。在完成测试之前，Jest将一直等到完成回调。

如果 done()永远不会调用，这个测试将失败，这也是你所希望发生的

```javascript
test('the data is peanut butter', done => {
    function callback(data) {
        expect(data).toBe('peanut butter');
        done();
    }

    fetchData(callback);
});
```

## Promises

如果您的代码使用 Promise，还有一个更简单的方法来处理异步测试。 只需要从您的测试返回一个Promise, Jest 会等待Promise。 如果Promise被拒绝，则测试将自动失败。

还是上面的例子，如果用 Promise处理请求，那么实现将是下面的样子：

```javascript
test('the data is peanut butter', () => {
    expect.assertions(1);
    return fetchData().then(data => {
        expect(data).toBe('peanut butter');
    });
});
```

assertions（1）代表的是在当前的测试中至少有一个断言（expect）是被调用的，否则判定为失败

一定要返回Promise - 如果你省略 return 语句，您的测试将在 fetchData 完成之前完成。

如果想要捕获Promise的异常。使用 .catch 方法。 请确保添加 expect.assertions 来验证一定数量的断言被调用。 因为有可能Promise执行了reject，catch是无法捕获到的。一个fulfilled态的Promise 不会让测试失败

```javascript
test('the fetch fails with an error', () => {
    expect.assertions(1);
    return fetchData().catch(e => expect(e).toMatch('error'));
});
```

### resolves / .rejects

在Jest 20.0.0+ 的版本中你可以使用```.resolves匹配器```在你的expect语句中，Jest将会等待一直到Promise被实现，如果承诺没有被实现，测试将自动失败。

```javascript
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter');
});
```

如果期望捕获Promise的异常使用 请使用```.rejects匹配器```

```javascript
test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error');
});
```

## Async/Await

你可以在测试中使用Async/Await。要编写一个async测试，只需在测试的函数前面使用async关键字。例如上面同样的fetchData场景可以使用下面的实现:

```javascript
test('the data is peanut butter', async () => {
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
    expect.assertions(1);
    try {
        await fetchData();
    } catch (e) {
        expect(e).toMatch('error');
    }
});
```

在Jest 20.0.0+ 的版本中可以将Async Await和 .resolves .rejects 结合起来

```javascript
test('the data is peanut butter', async () => {
    await expect(fetchData()).resolves.toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
    await expect(fetchData()).rejects.toThrow('error');
});
```

## 特别注意

- 在基于```Promise```，```Async/Await``` 的异步回调测试中，```Test回调函数```千万不要传```done```参数。否则会超时，导致测试失败。
- 当使用```.resolves```, ```.rejects```时，不需要使用expect.assertions。
- 如果使用```.catch```捕获Promise的异常。 请确保添加 expect.assertions 来验证一定数量的断言被调用。 因为有可能Promise执行了reject，catch是无法捕获到的。一个fulfilled态的Promise 不会让测试失败。

## expect.assertions

验证在测试期间是否调用了一定数量的断言。 这在测试异步代码时通常很有用，以确保实际调用回调中的断言。

[演示代码](../source_code/01)